quicker accesses

diff --git a/my_stuff/bash/aws_container_access b/my_stuff/bash/aws_container_access
--- a/my_stuff/bash/aws_container_access
+++ b/my_stuff/bash/aws_container_access
@@ -1,26 +1,48 @@
 #!/bin/bash
-region=$(dialog --stdout --menu "AWS Region" 20 70 18 \
-	eu-west-1 Irlanda eu-central-1 Frankfurt eu-west-2 Londres eu-south-1 Milan eu-west-3 Paris eu-north-1 Estocolmo \
-	us-east-1 Virginia us-east-2 Ohio us-west-1 California us-west-2 Oregon
-)
+check=$(aws sts get-caller-identity 2>/dev/null)
+if [[ "$?" != "0" ]]; then
+	echo "Credentials not present"
+	exit
+fi
+if [[ "$1" == "help" ]]; then
+	echo options: direct, simple or default
+	echo "no help ATM. Read the source code for now"
+	exit 0
+elif [[ "$1"=="direct" ]]; then
+	if [[ "$4" == "" ]]; then
+		echo 'required: direct <region> <cluster> <bash|sh>'
+		exit 1
+	fi
+	region="$2"
+	cluster="$3"
+	cmd="/bin/${4}"
+	select task in $(aws ecs list-tasks --region $region --cluster $cluster --query "taskArns[]" --output json | jq -Mr ".[]" | sed "s/^.*\///g"); do break; done
+elif [[ "$1"=="simple" ]]; then
+	#select continent in eu us; do echo;break; done
+	#select area in east west central; do echo;break; done
+	#select sub in 1 2 3; do echo;break; done
+	#region=${continent}-${area}-${sub}
+	select region in eu-central-1 eu-west-1 eu-west-2; do echo;break; done
+	select cluster in $(aws ecs list-clusters --region $region --query "clusterArns" --output json | jq -Mr ".[]" | sed -r "s/^.*\///"); do break; done
+	select task in $(aws ecs list-tasks --region $region --cluster $cluster --query "taskArns[]" --output json | jq -Mr ".[]" | sed "s/^.*\///g"); do break; done
+	select cmd in "/bin/sh" "/bin/bash"; do break; done
+else
+	region=$(dialog --stdout --menu "AWS Region" 20 70 18 \
+		eu-west-1 Irlanda eu-central-1 Frankfurt eu-west-2 Londres eu-south-1 Milan eu-west-3 Paris eu-north-1 Estocolmo \
+		us-east-1 Virginia us-east-2 Ohio us-west-1 California us-west-2 Oregon
+	)
 
-cluster=$(dialog --no-items --stdout --menu "Cluster" 12 30 18 \
-	$(aws ecs list-clusters --region $region --query "clusterArns" --output json | jq -Mr ".[]" | sed -r "s/^.*\///") \
-)
+	cluster=$(dialog --no-items --stdout --menu "Cluster" 12 30 18 \
+		$(aws ecs list-clusters --region $region --query "clusterArns" --output json | jq -Mr ".[]" | sed -r "s/^.*\///") \
+	)
 
-task=$(dialog --no-items --stdout --menu "Task" 20 40 18 \
-	$(aws ecs list-tasks --region $region --cluster $cluster --query "taskArns[]" --output json | jq -Mr ".[]" | sed "s/^.*\///g") \
-)
+	task=$(dialog --no-items --stdout --menu "Task" 20 40 18 \
+		$(aws ecs list-tasks --region $region --cluster $cluster --query "taskArns[]" --output json | jq -Mr ".[]" | sed "s/^.*\///g") \
+	)
 
-cmd=$(dialog --no-items --stdout --menu "Command" 10 10 9 "/bin/bash" "/bin/sh" )
+	cmd=$(dialog --no-items --stdout --menu "Command" 10 10 9 "/bin/bash" "/bin/sh" )
+fi
 
-#select continent in eu us; do echo;break; done
-#select area in east west central; do echo;break; done
-#select sub in 1 2 3; do echo;break; done
-#region=${continent}-${area}-${sub}
-#select cluster in $(aws ecs list-clusters --region $region --query "clusterArns" --output json | jq -Mr ".[]" | sed -r "s/^.*\///"); do break; done
-#select task in $(aws ecs list-tasks --region $region --cluster $cluster --query "taskArns[]" --output json | jq -Mr ".[]" | sed "s/^.*\///g"); do break; done
-#select cmd in "/bin/sh" "/bin/bash"; do break; done
 
 aws ecs execute-command --region $region --cluster $cluster --task $task --command "$cmd" --interactive
 
